name: attend_me
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  camera: ^0.10.0+2
  logging: ^1.0.2
  shared_preferences: ^2.0.15
  intl: ^0.18.0
  http: ^0.13.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/next.png
    - assets/Back.png 
    - assets/login.png 
    - assets/loginreal.png
    - assets/register.png
    - assets/camera_button.png
    - assets/human_computer_interface.png
    - assets/professionalism_at_work_place.png
    - assets/data_mining.png
    - assets/capstone_project.png
    - assets/IoT.png
    - assets/calender.png
    - assets/event.png
    - assets/leave_notes.png
    - assets/attendance_report.png
    - assets/profile.png

