# Generated by Django 5.0.7 on 2024-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=' images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
