# Generated by Django 5.0.7 on 2024-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='Default Batch', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_year',
            field=models.CharField(default='2024', max_length=4),
        ),
        migrations.AddField(
            model_name='student',
            name='face_data',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\IIMS COLLEGE\\Bcs 8th sem\\new'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='FirstName', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='LastName', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='model_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
