# Generated by Django 5.0.7 on 2024-08-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendme', '0004_student_studentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
